# actuator info part
info:
  name: springCoreFeaturesApp
  description: just a demo project for core features
  version: 1.0.0
  author: kk
  domain: facebook.com

# Work with the type-safe part
app-config:
  name: SpringBootApp
  description: Test Description
  version: 1.0.1
  security:
      jwt-secret: verysecured123
      expiration: 365
  kafka:
      topic: student-topic
      retry-count: 3


spring:
  # enable the virtual thread support from jdk 21+
  # optimize concurrent tasks from old tranditional thread
  # tranditional = take a lot of cpu power per task
  threads:
    virtual:
      enabled: true
  application:
    name: spring-core-features

# configuration for exposing endpoints of actuator
#server:
#  port: 9090
management:
  # used in order to allow getting information about our app
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans
      # include: '*' // Avoid using this on prod
server:
  port: 9090
