app-info:
  name: springCoreFeaturesApp
  version: 1.0.0
  developer: kk
  domain: facebook.com
  port: 9090

spring:
  # enable the virtual thread support from jdk 21+
  # optimize concurrent tasks from old tranditional thread
  # tranditional = take a lot of cpu power per task
  threads:
    virtual:
      enabled: true
  application:
    name: spring-core-features

# configuration for exposing endpoints of actuator
#server:
#  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans
      # include: '*' // Avoid using this on prod
server:
  port: "${app-info.port}"